curl -X POST http://localhost:8080/api/orders \d
-H "Content-Type: application/json" \d
-d '{
    "customerName":"Maria",
    "status":"CREATED",
    "items":[
      {
        "productName":"Notebook",
        "quantity":1,
        "unitPrice":4500.00
      },
      {
        "productName":"Mouse",
        "quantity":2,
        "unitPrice":1000.00
      }
    ]
  }'